import * as esbuild from "esbuild";
// import { umdWrapper } from "esbuild-plugin-umd-wrapper";
import fs from "fs";
import { platform } from "os";

const version =
  process.env.SEMANTIC_RELEASE_NEXT_VERSION ||
  JSON.parse(fs.readFileSync("./package.json")).version;

console.log("building version:", version);

const banner = `/**
 * md-to-shopify-rich-text v${version} - a markdown parser
 * Copyright (c) 2025-${new Date().getFullYear()}, dlxmj. (MIT Licensed)
 */

/**
 * DO NOT EDIT THIS FILE
 * The code in this file is generated from files in ./src/
 */
`;

function config(options) {
  return {
    entryPoints: ["md-to-shopify-rich-text/src/main.ts"],
    banner: {
      js: banner,
    },
    sourcemap: true,
    bundle: true,
    minify: true,
    // ...(options.format === "umd"
    //   ? {
    //       plugins: [
    //         umdWrapper({
    //           libraryName: "marked",
    //         }),
    //       ],
    //     }
    //   : {}),
    ...options,
  };
}

await esbuild.build(
  config({
    platform: "node",
    format: "cjs",
    outfile: "dist/main.cjs",
  }),
);

await esbuild.build(
  config({
    platform: "node",
    format: "esm",
    outfile: "dist/main.mjs",
  }),
);
